# fly.toml app configuration file generated for maily on 2025-06-06T10:41:36+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maily'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  internal_port = 5000
  force_https = true

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'
 