# fly.toml app configuration file generated for maily on 2025-06-05T20:47:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maily'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '5000'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Services for Fly.io
[[services]]
  internal_port = 5000
  protocol = 'tcp'

[[services.ports]]
port = 80
handlers = ['http']

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
soft_limit = 25
hard_limit = 50

[services.http_checks]
path = "/health"
interval = "10s"
timeout = "2s"
method = "get"
