name: Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions@1
        with:
          args: "deploy --remote-only -a maily"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 